version: "3.9"

services:
  user-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  user-service:
    container_name: user-service
    build: ./services/user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/users
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - user-db

  agent-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: agents
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  agent-service:
    container_name: agent-service
    build: ./services/agent-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://agent-db:5432/agents
      - SPRING_DATASOURCE_USERNAME=agent
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - agent-db

  audio-service:
    build: ./services/audio-service
    ports:
      - "8083:8083"

  frontend-nextjs:
    build: ./frontend-nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_USERS=http://localhost:8081/api/users
      - NEXT_PUBLIC_API_AGENTS=http://localhost:8082/api/agents
      - NEXT_PUBLIC_AUDIO_WS=ws://localhost:8083
      - AGENT_SERVICE_URL=http://nginx/api/agents
      - USER_SERVICE_URL=http://nginx/api/users

  lk-agent:
    build:
      context: ./services/multimodal-agent-node
    ports:
      - "8084:8084"

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-nextjs
      - user-service
      - agent-service
      - audio-service
